
import React, { useState } from 'react';
import { OrderItem } from '../types';
import { jsPDF } from 'jspdf';

interface OrderTrackingProps {
  orders: OrderItem[];
}

const OrderTracking: React.FC<OrderTrackingProps> = ({ orders }) => {
  const [previewDoc, setPreviewDoc] = useState<{ type: 'invoice' | 'report', order: OrderItem } | null>(null);
  const [refundOrder, setRefundOrder] = useState<OrderItem | null>(null);
  const [refundReason, setRefundReason] = useState('');
  const [refundStep, setRefundStep] = useState<'form' | 'processing' | 'success'>('form');

  if (orders.length === 0) {
    return (
      <div className="p-6 h-full flex flex-col items-center justify-center text-gray-500 dark:text-gray-400">
        <div className="w-24 h-24 bg-gray-100 dark:bg-gray-800 rounded-full flex items-center justify-center mb-6">
          <svg className="w-12 h-12 text-gray-300 dark:text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2H2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" /></svg>
        </div>
        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-2">No Active Orders</h2>
        <p className="text-center max-w-xs">Your medicine orders, lab test bookings, and appointments will appear here.</p>
      </div>
    );
  }

  const handlePreview = (e: React.MouseEvent, type: 'invoice' | 'report', order: OrderItem) => {
    e.preventDefault();
    setPreviewDoc({ type, order });
  };

  const closePreview = () => setPreviewDoc(null);

  const downloadPDF = () => {
    if (!previewDoc) return;
    const doc = new jsPDF();
    const { order, type } = previewDoc;

    // Stylish Header
    doc.setFillColor(13, 148, 136);
    doc.rect(0, 0, 210, 45, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("MEDASSIST AI", 20, 25);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(type === 'invoice' ? "TAX INVOICE" : "LABORATORY REPORT", 20, 35);
    doc.text(`ID: #${order.id}`, 190, 25, { align: 'right' });
    doc.text(`Date: ${order.date.toLocaleDateString()}`, 190, 35, { align: 'right' });

    // Customer Info
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(type === 'invoice' ? "BILLED TO:" : "PATIENT DETAILS:", 20, 65);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text("Rahul Sharma", 20, 75);
    doc.text("Age: 28 / Male", 20, 82);
    doc.text("Patna, Bihar, India", 20, 89);

    doc.line(20, 100, 190, 100);

    // Dynamic Data
    if (type === 'invoice') {
      doc.setFont("helvetica", "bold");
      doc.text("ITEM DESCRIPTION", 20, 115);
      doc.text("PRICE", 190, 115, { align: 'right' });
      doc.line(20, 118, 190, 118);
      
      doc.setFont("helvetica", "normal");
      const items = order.details.split(',');
      items.forEach((item, i) => {
        doc.text(item.trim(), 20, 130 + (i * 10));
      });

      doc.line(120, 180, 190, 180);
      doc.text(`Subtotal:`, 120, 190);
      doc.text(`Rs. ${Math.round(order.amount * 0.88)}`, 190, 190, { align: 'right' });
      doc.text(`GST (12%):`, 120, 200);
      doc.text(`Rs. ${Math.round(order.amount * 0.12)}`, 190, 200, { align: 'right' });
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.text(`TOTAL: Rs. ${order.amount}`, 190, 220, { align: 'right' });
    } else {
      doc.setFont("helvetica", "bold");
      doc.text("TEST RESULTS", 20, 115);
      doc.line(20, 118, 190, 118);
      doc.setFont("helvetica", "normal");
      doc.text(`Test Name: ${order.title}`, 20, 130);
      doc.text("Sample: Blood Serum", 20, 140);
      doc.text("Analyte 1: 12.4 mg/dL (Ref: 10-15)", 20, 150);
      doc.text("Analyte 2: 0.85 mg/dL (Ref: 0.5-1.2)", 20, 160);
      doc.setTextColor(13, 148, 136);
      doc.text("STATUS: CLINICALLY STABLE", 20, 180);
    }

    doc.setTextColor(100, 116, 139);
    doc.setFontSize(8);
    doc.text("This document is generated by MedAssist AI. GSTIN: 10AAAAA0000A1Z5", 105, 285, { align: 'center' });

    doc.save(`MedAssist_${type}_${order.id}.pdf`);
    closePreview();
  };

  const handleRefundRequest = () => {
    if (!refundReason) return;
    setRefundStep('processing');
    setTimeout(() => {
      setRefundStep('success');
    }, 2000);
  };

  const isEligibleForRefund = (order: OrderItem) => {
    const diffDays = (new Date().getTime() - order.date.getTime()) / (1000 * 3600 * 24);
    return order.type !== 'doctor_appointment' && diffDays < 7 && !order.status.toLowerCase().includes('refund');
  };

  return (
    <div className="p-6 pb-24 md:pb-6 max-w-5xl mx-auto w-full overflow-y-auto">
      <header className="mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Track Orders</h1>
          <p className="text-gray-500 dark:text-gray-400">Real-time status of your medicines and appointments.</p>
        </div>
        <div className="bg-teal-50 dark:bg-teal-900/20 px-4 py-2 rounded-xl border border-teal-100 dark:border-teal-800">
           <p className="text-[10px] font-black text-teal-600 dark:text-teal-400 uppercase tracking-widest">Refund Policy</p>
           <p className="text-xs font-bold text-teal-800 dark:text-teal-200">Eligible within 7 days</p>
        </div>
      </header>

      <div className="space-y-6">
        {orders.map((order) => (
          <div key={order.id} className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-700 p-6 transition-all hover:shadow-md relative overflow-hidden">
            
            {order.status.toLowerCase().includes('refund') && (
              <div className="absolute top-0 left-0 right-0 bg-amber-500 text-white text-[10px] font-black uppercase tracking-[0.2em] py-1 text-center">
                Refund in Progress
              </div>
            )}

            <div className="flex flex-col md:flex-row justify-between md:items-center mb-6 gap-4">
              <div className="flex items-start gap-4">
                <div className={`w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0 ${
                  order.type === 'medicine' ? 'bg-teal-50 dark:bg-teal-900/30 text-teal-600 dark:text-teal-400' : 
                  order.type === 'lab_test' ? 'bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400' :
                  'bg-purple-50 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400'
                }`}>
                  {order.type === 'medicine' ? (
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.384-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" /></svg>
                  ) : order.type === 'lab_test' ? (
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                  ) : (
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
                  )}
                </div>
                <div>
                  <h3 className="font-bold text-gray-900 dark:text-white text-lg">{order.title}</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400 mb-1">{order.details}</p>
                  <p className="text-xs text-gray-400 dark:text-gray-500">Order ID: #{order.id} • {order.date.toLocaleDateString()}</p>
                </div>
              </div>
              <div className="flex flex-col items-end">
                <span className="text-xl font-bold text-gray-900 dark:text-white">₹{order.amount}</span>
                <span className={`px-3 py-1 rounded-full text-xs font-bold uppercase mt-1 ${
                  order.status === 'Delivered' || order.status === 'Completed' || order.status === 'Visit Completed'
                    ? 'bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400' 
                    : 'bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400'
                }`}>
                  {order.status}
                </span>
              </div>
            </div>

            <div className="relative mb-6">
              <div className="hidden md:flex justify-between items-center relative z-10 px-4">
                <div className="absolute left-0 right-0 top-3 h-0.5 bg-gray-200 dark:bg-gray-700 -z-10 mx-8"></div>
                 <div 
                   className="absolute left-0 top-3 h-0.5 bg-teal-500 -z-10 mx-8 transition-all duration-1000"
                   style={{ width: `${(order.steps.filter(s => s.isCompleted).length - 1) / (order.steps.length - 1) * 100}%` }}
                 ></div>

                {order.steps.map((step, idx) => (
                  <div key={idx} className="flex flex-col items-center">
                    <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center transition-colors duration-300 ${
                      step.isCompleted 
                        ? 'border-teal-500 bg-teal-500' 
                        : 'border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800'
                    }`}>
                      {step.isCompleted && (
                        <svg className="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" /></svg>
                      )}
                    </div>
                    <div className="text-center mt-2">
                      <p className={`text-xs font-bold ${step.isCompleted ? 'text-teal-700 dark:text-teal-400' : 'text-gray-400 dark:text-gray-500'}`}>{step.label}</p>
                      {step.timestamp && <p className="text-[10px] text-gray-400 dark:text-gray-600">{step.timestamp}</p>}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="mt-6 flex flex-wrap justify-between items-center gap-4">
              <div className="flex flex-wrap gap-3">
                {order.reportUrl && (
                  <button 
                    onClick={(e) => handlePreview(e, 'report', order)}
                    className="flex items-center px-4 py-2.5 bg-teal-50 dark:bg-teal-900/30 text-teal-700 dark:text-teal-300 rounded-xl text-sm font-medium hover:bg-teal-100 dark:hover:bg-teal-800 transition-colors border border-teal-100 dark:border-teal-800"
                  >
                    <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                    View Report
                  </button>
                )}
                {order.invoiceUrl && (
                  <button 
                    onClick={(e) => handlePreview(e, 'invoice', order)}
                    className="flex items-center px-4 py-2.5 bg-gray-50 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-xl text-sm font-medium hover:bg-gray-100 dark:hover:bg-gray-600 transition-colors border border-gray-200 dark:border-gray-600"
                  >
                    <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" /></svg>
                    Invoice
                  </button>
                )}
              </div>

              {isEligibleForRefund(order) && (
                <button 
                  onClick={() => {
                    setRefundOrder(order);
                    setRefundStep('form');
                    setRefundReason('');
                  }}
                  className="flex items-center px-4 py-2.5 text-rose-600 dark:text-rose-400 text-xs font-black uppercase tracking-widest hover:bg-rose-50 dark:hover:bg-rose-900/20 rounded-xl transition-all"
                >
                  <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 15v-1a4 4 0 00-4-4H8m0 0l3 3m-3-3l3-3m9 14V5a2 2 0 00-2-2H6a2 2 0 00-2 2v16l4-2 4 2 4-2 4 2z" /></svg>
                  Request Refund
                </button>
              )}
            </div>
          </div>
        ))}
      </div>

      {previewDoc && (
        <div className="fixed inset-0 z-[100] bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in duration-200">
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col overflow-hidden transition-colors">
            <div className="bg-gray-800 dark:bg-gray-900 text-white p-4 flex justify-between items-center">
              <h3 className="text-lg font-bold flex items-center">
                {previewDoc.type === 'invoice' ? "Invoice Preview" : "Report Preview"}
              </h3>
              <button onClick={closePreview} className="text-gray-400 hover:text-white transition-colors">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-8 bg-gray-100 dark:bg-gray-900">
              <div className="bg-white shadow-lg p-8 mx-auto max-w-lg min-h-[500px] text-sm text-gray-800">
                <h2 className="text-2xl font-bold text-teal-600 mb-6">{previewDoc.type === 'invoice' ? 'TAX INVOICE' : 'LAB REPORT'}</h2>
                <div className="space-y-4">
                  <p><strong>Date:</strong> {previewDoc.order.date.toLocaleDateString()}</p>
                  <p><strong>Order ID:</strong> #{previewDoc.order.id}</p>
                  <p><strong>Customer:</strong> Rahul Sharma</p>
                  <hr />
                  <p><strong>Details:</strong> {previewDoc.order.details}</p>
                  <p className="text-lg"><strong>Total Amount Paid:</strong> ₹{previewDoc.order.amount}</p>
                </div>
              </div>
            </div>

            <div className="bg-white dark:bg-gray-800 p-4 border-t border-gray-100 dark:border-gray-700 flex justify-end gap-3">
              <button 
                onClick={closePreview}
                className="px-6 py-2.5 rounded-xl border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 font-medium hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
              >
                Close
              </button>
              <button 
                onClick={downloadPDF}
                className="px-6 py-2.5 rounded-xl bg-teal-600 text-white font-medium hover:bg-teal-700 transition-colors flex items-center shadow-lg shadow-teal-200 dark:shadow-none"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                Download PDF
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default OrderTracking;